# Generated by Django 5.2.11 on 2026-02-18 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_servico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='preco',
        ),
    ]
