# Generated by Django 5.2.11 on 2026-02-19 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_produto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='servicos/'),
        ),
    ]
